logging:
 file:
  path: logs
 level:
  root: info
  org:
   springframework:
    ldap: DEBUG
    security:
     ldap: DEBUG


server:
 forward-headers-strategy: native
 port: 9442
 ssl:
  enabled: true
  key-alias: server
  key-store: classpath:server-keystore.p12
  key-store-password: changeitnow

  

spring:
 application:
  name: SecureAtmLoggerSpringBootSSO
 banner:
  location: banner.txt
 datasource:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  password: password
  url: jdbc:sqlserver://localhost:1433;databaseName=SecureAtmIssueLogger;encrypt=true;trustServerCertificate=true
  username: ikenna
 jpa:
   generate-ddl: true
   properties:
    hibernate:
     ddl-auto: update
     dialect: org.hibernate.dialect.SQLServerDialect
     format-sql: true
     naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImplnaming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl     
   show-sql: true
 ldap:
  password: secret
  urls: ldaps://localhost:10636
  username: uid=admin,ou=system
 mail:
  default-encoding: UTF-8
  host: smtp.mailtrap.io
  password: fd5346e2206c67
  port: 2525
  properties:
   mail:
    smtp:
     connectiontimeout: 100000
     writetimeout: 100000
  protocol: smtp
  username: 6de7c8e7b17655
 messages:
  basename: messages
  encoding: UTF-8
 security:
    user:
      name: root
      password: Ebank@12345$$

app:
 jwt:
  expiration-ms: 86400000
  secret: your-ultra-secure-and-very-long-secret-key-32-bytes-minimum
atm:
 support:
  email: ATMServices@fidelitybank.ng;Aderinsola.Adeyeye@fidelitybank.ng












